# Generated by Django 5.1.4 on 2026-03-24 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color_hex',
            field=models.CharField(default='#0F766E', max_length=7, validators=[django.core.validators.RegexValidator(message='Use a valid hex color such as #0EA5E9.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
